#!/bin/bash
# This script should contain the command(s) nessesary to switch on the
# nVidia card.
# Please note that the acpi_call module is need for these operations:
#
# http://linux-hybrid-graphics.blogspot.com/2010/07/using-acpicall-module-to-switch-onoff.html

# acpi_call method to turn ON nVidia Card
NV_SWITCH_ON=  # Put your method here

modprobe acpi_call
if ! lsmod | grep -q acpi_call; then
    echo "Error: acpi_call module not loaded,"
    echo "you won't be able to turn on nVidia card"
    exit
fi

acpi_call () {
    echo "$*" > /proc/acpi/call
    result=$(cat /proc/acpi/call)
    case "$result" in
     Error*)
      echo "Enabling nVidia Card failed ($result)."
      ;;
     *)
      echo "Enabling nVidia Card Succeded."
     ;;
    esac
}

echo _PS0 $(acpi_call $NV_SWITCH_ON)
modprobe nvidia-current
