#!/bin/bash

# This script will watch for active instances of "optirun" and enable/disable 
# the bumblebee daemon.

. /etc/bumblebee/bumblebee.conf
. /etc/rc.d/functions

enable_bumblebee() {
     /sbin/rc.d start bumblebee
}

disable_bumblebee() {
     /sbin/rc.d stop bumblebee
}

while :
do
     if pidof -x optirun ; then
          if [ ! ck_status bumblebee ]; then
               enable_bumblebee
          fi
     else
          if [ ck_status bumblebee ]; then
               disable_bumblebee
          fi
     fi
     sleep 1
done
