#!/bin/sh

ENABLECARD=/usr/local/bin/bumblebee-enablecard
DISABLECARD=/usr/local/bin/bumblebee-disablecard

####
## This script disables nVidia card if no optirun is running.
####
if ! pgrep optirun >/dev/null; then
	$ENABLECARD
	$DISABLECARD
fi
