#!/bin/bash

ENABLECARD=/usr/local/bin/bumblebee-enablecard
DISABLECARD=/usr/local/bin/bumblebee-disablecard

####
## This script disables Nvidia card if no optirun is running.
####
if [  `ps aux |grep optirun|wc -l` -lt 2 ]; then
	$ENABLECARD
	$DISABLECARD
fi
