#!/bin/bash
 
#
# ----------------------------------------------------------------------------
# "THE BEER-WARE LICENSE" (Revision 42):
# <mj@casalogic.dk> wrote this file. As long as you retain this notice you
# can do whatever you want with this stuff. If we meet some day, and you think
# this stuff is worth it, you can buy me a beer in return Martin Juhl 
# ----------------------------------------------------------------------------
#

#    This file is part of bumblebee.
#
#    bumblebee is free software: you can redistribute it and/or modify
#    it under the terms of the GNU General Public License as published by
#    the Free Software Foundation, either version 3 of the License, or
#    (at your option) any later version.
#
#    bumblebee is distributed in the hope that it will be useful,
#    but WITHOUT ANY WARRANTY; without even the implied warranty of
#    MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
#    GNU General Public License for more details.
#
#    You should have received a copy of the GNU General Public License
#    along with bumblebee.  If not, see <http://www.gnu.org/licenses/>.
#
  

ROOT_UID=0

if [ `cat /etc/issue |grep -nir fedora |wc -l` -gt 0 ]; then
 DISTRO=FEDORA
 BASHRC=/etc/bashrc
elif [ `cat /etc/issue |grep -nir ubuntu |wc -l` -gt 0 ]; then
 DISTRO=UBUNTU
 BASHRC=/etc/bash.bashrc  
elif [ `cat /etc/issue |grep -nir opensuse |wc -l` -gt 0 ]; then
 DISTRO=OPENSUSE
 BASHRC=/etc/bash.bashrc
elif [ `cat /etc/issue |grep -nir debian |wc -l` -gt 0 ]; then
 DISTRO=DEBIAN
 BASHRC=/etc/bash.bashrc
fi
    
ARCH=`uname -m`
MODPROBE=`which modprobe`

if [ $UID != $ROOT_UID ]; then
    echo "You don't have sufficient privileges to run this script."
    echo
    echo "Please run the script with: sudo bumblebee-uninstall"
    exit 1
fi

if [ $HOME = /root ]; then
    echo "Do not run this script as the root user"
    echo
    echo "Please run the script with: sudo bumblebee-uninstall"
    exit 2
fi

echo "Welcome to the bumblebee uninstallation"
echo "Licensed under BEER-WARE License and GPL"
echo
echo "This script will remove bumblebee completely"
echo "and also clean up after earlier versions"
echo
if [ $DISTRO = FEDORA ] && [ "$ARCH" = "x86_64" ]; then
    echo "Uninstalling will most likely kill your X-session"
    echo "please make sure that all your data is saved"
    echo
fi
echo "Are you sure you want to proceed?? (Y/N)"
echo

read answer

case "$answer" in

y | Y )
;;
  
*)
exit 0
;;
esac

#Kill the nvidia X server
/etc/init.d/bumblebee stop

sleep 5

echo 
if [ $DISTRO = UBUNTU  ] || [ $DISTRO = DEBIAN  ]; then
 echo "Removing nVidia driver package"
 echo
 apt-get -y --purge remove nvidia-current
 echo "Removing VirtualGL package"
 echo
 dpkg -r VirtualGL
 update-rc.d -f bumblebee remove
 rm /etc/pm/power.d/bumblebee-disablecard-on-powerup
elif [ $DISTRO = OPENSUSE ]; then
 echo "Removing VirtualGL package"
 echo
 yum -y remove VirtualGL
 chkconfig bumblebee off 
elif [ $DISTRO = FEDORA ]; then
    echo "Removing VirtualGL package"
    echo
    yum -y remove VirtualGL
    if [ -f /etc/profile.d/virtualgl.sh ]; then
        rm /etc/profile.d/virtualgl.sh
    fi
    chkconfig bumblebee off 
    # New method for x86_64 but still the old one for i686
    if [ "$ARCH" = "x86_64" ]; then
        echo "Removing nVidia driver package"
        ${MODPROBE} -r nvidia
        /usr/lib64/nvidia-current/bin/nvidia-installer -s --uninstall
    fi
fi

#Unload the nvidia module
${MODPROBE} -r nvidia

echo
echo "Restoring old configuration"
if [ -f ${BASHRC}.optiorig ]; then
    mv $BASHRC.optiorig $BASHRC
fi
if [ -f /etc/modprobe.d/blacklist.conf.optiorig ]; then
    mv /etc/modprobe.d/blacklist.conf.optiorig /etc/modprobe.d/blacklist.conf
fi
if [ -f /etc/modules.optiorig ]; then
    mv /etc/modules.optiorig /etc/modules
fi

if [ -f /etc/X11/xorg.conf.optiorig ]; then
    mv -f /etc/X11/xorg.conf.optiorig /etc/X11/xorg.conf
fi
rm /etc/X11/xorg.conf.nvidia

rm -rf /etc/X11/xdm-optimus
rm -rf /etc/X11/bumblebee
if [ -f /etc/init.d/xdm-optimus ]; then
    rm /etc/init.d/xdm-optimus
fi
rm /etc/init.d/bumblebee
if [ -f /etc/modprobe.d/virtualgl.conf ]; then
    rm /etc/modprobe.d/virtualgl.conf
fi
if [ -f /usr/local/bin/optimusXserver ]; then
    rm /usr/local/bin/optimusXserver
fi
rm /usr/local/bin/bumblebee-bugreport
if [ -f /usr/bin/xdm-optimus ]; then
    rm /usr/bin/xdm-optimus
fi
rm -rf /usr/lib64/nvidia-current
rm -rf /usr/lib/nvidia-current
rm -rf /usr/lib/bumblebee
rm /usr/local/bin/optirun*
rm /usr/local/bin/bumblebee-disablecard-on-powerup
rm /usr/bin/vglclient-service
rm /etc/modprobe.d/nouveau-blacklist.conf
rm -rf /usr/share/doc/bumblebee
rm -rf /usr/local/bin/bumblebee*
rm -rf /etc/default/bumblebee*
if [ -d /opt/prime-ng ]; then
    rm -rf /opt/prime-ng
fi
if [ -d /opt/bumblebee ]; then
    rm -rf /opt/bumblebee
fi

if [ `dkms status |grep acpi_call | wc -l` > 0 ]; then
 dkms uninstall -m acpi_call -v `dkms status |grep acpi_call |cut -f2 -d,`  
 dkms remove -m acpi_call -v `dkms status |grep acpi_call |cut -f2 -d,` --all
fi

rm /etc/alternatives/xorg_extra_modules-bumblebee 
ln -s /usr/lib/nvidia-current/xorg /etc/alternatives/xorg_extra_modules

ldconfig

if [ -f $HOME/.kde/Autostart/vglclient-service ]; then
 rm $HOME/.kde/Autostart/vglclient-service
fi

if [ -f $HOME/.config/autostart/vglclient-service ]; then
 rm $HOME/.config/autostart/vglclient-service
fi

grep -Ev 'VGL|optirun' $HOME/.bashrc > $HOME/.oldbashrc
mv $HOME/.oldbashrc $HOME/.bashrc
chown $USER:$USER $HOME/.bashrc
grep -Ev 'bumblebee' /etc/sudoers > /etc/sudoers.optiorig
mv /etc/sudoers.optiorig /etc/sudoers
chmod 0440 /etc/sudoers

killall -9 vglclient

rm -rf /etc/bash_completion.d/optirun*

echo
echo "bumblebee has been uninstalled :("
echo

rm /etc/bumblebee
