#!/bin/bash
# This script should contain the command(s) nessesary to switch off the
# nVidia card.
# As an example i've included the script for my Alienware M11X R2..
# Please note that the acpi_call module is need for these operations:
#
# http://linux-hybrid-graphics.blogspot.com/2010/07/using-acpicall-module-to-switch-onoff.html

#rmmod nvidia
#modprobe acpi_call

#if ! lsmod | grep -q acpi_call; then
#    echo "Error: acpi_call module not loaded"
#    exit
#fi

#acpi_call () {
#    echo "$*" > /proc/acpi/call

#    result=$(cat /proc/acpi/call)
#    case "$result" in
#     Error*)       
#      echo "Disabling nVidia Card failed ($result)."
#      ;;                          
#     *)                                   
#      echo "Disabling nVidia Card Succeded."                                                                                
#     ;;                                                                   
#    esac   
#}

#echo NVOP $(acpi_call "\_SB.PCI0.P0P2.PEGP.NVOP 0 0x100 0x1A {255,255,255,255}")
#echo _PS3 $(acpi_call "\_SB.PCI0.P0P2.PEGP._PS3")
